"""create resumes table

Revision ID: 74ed202db0c6
Revises: 
Create Date: 2026-09-18 14:06:25.625783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74ed202db0c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('applicant_name', sa.String(length=100), nullable=False),
    sa.Column('target_position', sa.String(length=100), nullable=False),
    sa.Column('tone', sa.String(length=32), nullable=False),
    sa.Column('section_count', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.String(length=50), nullable=False),
    sa.Column('template_overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_density', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resumes')
    # ### end Alembic commands ###
